asdf

diff --git a/.github/workflows/master-build.yaml b/.github/workflows/master-build.yaml
--- a/.github/workflows/master-build.yaml
+++ b/.github/workflows/master-build.yaml
@@ -2,8 +2,7 @@ name: terragrunt apply
 
 on:
   push:
-    branches:
-      - master
+    branches: master
 
 jobs:
   build-matrix:
@@ -16,7 +15,7 @@ jobs:
         with:
           fetch-depth: 2
 
-      - name: get parent directory and set matrix
+      - name: set matrix of build jobs
         id: set-matrix
         run: |
           git diff --name-only HEAD^ HEAD > files.txt
@@ -38,12 +37,10 @@ jobs:
           tf_config="{\"include\":[$tf_config]}"
           echo "::set-output name=matrix::$tf_config"
 
-  terragrunt-run:
+
+  apply:
     needs: [build-matrix]
     runs-on: [self-hosted, linux]
-    #container:
-    #  image: azulinho/tg
-      #options: --user 1000
     strategy:
       matrix: ${{fromJson(needs.build-matrix.outputs.matrix)}}
       fail-fast: false
@@ -52,23 +49,76 @@ jobs:
         uses: actions/checkout@v2
         with:
           fetch-depth: 1
-      - name: get parent directory and set matrix
-        id: set-matrix
+
+      - name: run terragrunt apply
+        id: terragrunt-apply
+        env:
+          AWS_ACCOUNTS_KEYS: ${{ secrets.AWS_ACCOUNTS_ACCESS_KEYS }}
         run: |
+          set -o pipefail +e
           echo "matrix is: ${{ needs.build-matrix.outputs.matrix }}"
           echo "my job is: ${{ matrix.tf_config }}"
-          if ( echo "${{ matrix.tf_config }}" | grep namespace ); then
+          if ( echo "${{ matrix.tf_config }}" | grep "aws/" ); then
             cd ${{ matrix.tf_config }}
-            tgenv install
-            tfenv install
+
             # find out the account we need to update
             # aws/< account name >/< env >/< tf component >/
-            export AWS_ACCOUNT_NAME=`echo "${{ matrix.tf_config }}" | cut -f2 -d "/" `
+            export AWS_ACCOUNT_NAME=`echo "${{ matrix.tf_config }}" | cut -f2 -d "/"`
 
             # retrieve the creds from the env
-            export AWS_ACCESS_KEY_ID=`echo $AWS_ACCOUNT_NAME | cut -f1 -d ":"  `
-            export AWS_SECRET_ACCESS_KEY=`echo $AWS_ACCOUNT_NAME | cut -f2 -d ":"  `
+            export AWS_ACCESS_KEY_ID=`echo $AWS_ACCOUNT_KEYS | grep "$AWS_ACCOUNT_NAME" | cut -f2 -d ":"`
+            export AWS_SECRET_ACCESS_KEY=`echo $AWS_ACCOUNT_KEYS | grep "$AWS_ACCOUNT_NAME" | cut -f3 -d ":"`
+            export TGENV_NO_COLOR=true
+            export TFENV_NO_COLOR=true
 
-            terragrunt init
-            terragrunt apply --auto-approve
+            echo "# OUTPUT FOR JOB: ${{matrix.tf_config}}" > log.txt
+            echo >> log.txt
+            echo >> log.txt
+
+            # we disabled -e , so that we can fail and still collect the output
+            # from all failed actions
+            tgenv install 2>&1 | tee -a log.txt
+            let rc=$rc+$?
+
+            if [ $rc -lt 1 ]; then
+              tfenv install 2>&1 | tee -a log.txt
+              let rc=$?
+            fi
+
+            if [ $rc -lt 1 ]; then
+              terragrunt init -no-color 2>&1 | tee -a log.txt
+              let rc=$?
+            fi
+
+            if [ $rc -lt 1 ]; then
+              terragrunt apply -no-color -auto-approve 2>&1 | tee -a log.txt
+              let rc=$?
+            fi
+
+            # https://github.community/t/set-output-truncates-multiline-strings/16852/6
+            OUTPUT=$(cat log.txt)
+            OUTPUT="${OUTPUT//'%'/'%25'}"
+            OUTPUT="${OUTPUT//$'\n'/'%0A'}"
+            OUTPUT="${OUTPUT//$'\r'/'%0D'}"
+
+            echo "::set-output name=content::$OUTPUT"
+
+            if [ $rc -lt 1 ]; then
+              echo "::set-output name=emoji:: "
+            else
+              echo "::set-output name=emoji::-1"
+            fi
+
+            exit $rc
           fi
+
+      - name: Slack Notification
+        id: slack
+        if: ${{ always() }}
+        uses: act10ns/slack@v1
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
+        with:
+          status: ${{ job.status }}
+          steps: ${{ toJson(steps) }}
+          channel: '#scratch0'
